/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as OrderRouteImport } from './routes/order'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as DetailIdRouteImport } from './routes/detail.$id'
import { Route as ApiPublicWebhookPaymentRouteImport } from './routes/api/public/webhook/payment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailIdRoute = DetailIdRouteImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhookPaymentRoute = ApiPublicWebhookPaymentRouteImport.update({
  id: '/api/public/webhook/payment',
  path: '/api/public/webhook/payment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/kitchen': typeof KitchenRoute
  '/order': typeof OrderRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/detail/$id': typeof DetailIdRoute
  '/api/public/webhook/payment': typeof ApiPublicWebhookPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/kitchen': typeof KitchenRoute
  '/order': typeof OrderRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/detail/$id': typeof DetailIdRoute
  '/api/public/webhook/payment': typeof ApiPublicWebhookPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/kitchen': typeof KitchenRoute
  '/order': typeof OrderRoute
  '/settings': typeof SettingsRoute
  '/wallet': typeof WalletRoute
  '/detail/$id': typeof DetailIdRoute
  '/api/public/webhook/payment': typeof ApiPublicWebhookPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/favorites'
    | '/history'
    | '/kitchen'
    | '/order'
    | '/settings'
    | '/wallet'
    | '/detail/$id'
    | '/api/public/webhook/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/favorites'
    | '/history'
    | '/kitchen'
    | '/order'
    | '/settings'
    | '/wallet'
    | '/detail/$id'
    | '/api/public/webhook/payment'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/favorites'
    | '/history'
    | '/kitchen'
    | '/order'
    | '/settings'
    | '/wallet'
    | '/detail/$id'
    | '/api/public/webhook/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  HistoryRoute: typeof HistoryRoute
  KitchenRoute: typeof KitchenRoute
  OrderRoute: typeof OrderRoute
  SettingsRoute: typeof SettingsRoute
  WalletRoute: typeof WalletRoute
  DetailIdRoute: typeof DetailIdRoute
  ApiPublicWebhookPaymentRoute: typeof ApiPublicWebhookPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detail/$id': {
      id: '/detail/$id'
      path: '/detail/$id'
      fullPath: '/detail/$id'
      preLoaderRoute: typeof DetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhook/payment': {
      id: '/api/public/webhook/payment'
      path: '/api/public/webhook/payment'
      fullPath: '/api/public/webhook/payment'
      preLoaderRoute: typeof ApiPublicWebhookPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  HistoryRoute: HistoryRoute,
  KitchenRoute: KitchenRoute,
  OrderRoute: OrderRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRoute,
  DetailIdRoute: DetailIdRoute,
  ApiPublicWebhookPaymentRoute: ApiPublicWebhookPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
